### ISSUE TITLE
Sprint 2-1 [17/11/05]

### ISSUE THREAD

**Issue by markraven** [Chrispy21/MonogameBallgame#25]
- [x] **Felszedhető tárgyak hozzáadása**
- [x] -Életpont növelő / Collectible Health Points
- [x] -Több labda / More Balls
- [x] -Fegyveres ütő / Racket with a Gun
- [x] -Ütő meghosszabbítása / Longer Racket

Életpont növelő, hogy a felhasználónak lehetősége legyen életpontjainak növelésére.
Több labda hozzáadása, a játék nehézségének növelése szempontjából.
Fegyverrel rendelkező ütő hozzáadása, a játék nehézségének könnyítése szempontjából.
Ütő meghosszabbító tárgy hozzáadása.

**Comment by sdavid18** [comment]
A felvehető tárgyak működnek.
