### ISSUE TITLE
Dokumentáció elkészítése

### ISSUE THREAD

**Issue by markraven** [Chrispy21/MonogameBallgame#38]
- [x] Funkcionális specifikáció

- [x] Árajánlat

- [x] Követelményspecifikáció

- [x] Ajánlat

- [x] Alfa teszt jegyzőkönyv

- [x] Béta teszt jegyzőkönyv

- [x] Jegyzőkönyv

- [x] Használati útmutató

- [x] Tesztelési terv

- [x] Ütemterv

- [x] Rendszerterv

**Comment by markraven** [comment]
Jegyzőkönyv becsült munkaideje: 2 óra.

**Comment by markraven** [comment]
Jegyzőkönyv munkaideje: 2 óra.

**Comment by Chrispy21** [comment]
Használati útmutató becsült ideje: 1 óra

**Comment by Chrispy21** [comment]
Használati útmutató munkaideje: 50 perc

**Comment by Chrispy21** [comment]
Követelmény specifikáció becsült ideje: 1 óra 30 perc

**Comment by Chrispy21** [comment]
Követelmény specifikáció munkaideje: 1 óra 40 perc

**Comment by markraven** [comment]
Funkcionális specifikáció becsült munkaideje: 3 óra

**Comment by markraven** [comment]
Funkcionális specifikáció munkaideje: 3 óra

**Comment by markraven** [comment]
Tesztelési terv becsült munkaideje: 2 óra

**Comment by markraven** [comment]
Tesztelési terv munkaideje: 1 óra 35 perc

**Comment by ChaosOMFG** [comment]
Ütemterv terv becsült munkaideje: 1 óra 30 perc

**Comment by ChaosOMFG** [comment]
Ütemterv terv munkaideje: 1 óra

**Comment by markraven** [comment]
Árajánlat becsült munkaideje: 3 óra

**Comment by markraven** [comment]
Árajánlat munkaideje: 3 óra

**Comment by markraven** [comment]
Ajánlat becsült munkaideje: 2 óra

**Comment by markraven** [comment]
Ajánlat munkaideje: 1 óra

**Comment by markraven** [comment]
Rendszerterv becsült munkaideje: 10 óra

**Comment by markraven** [comment]
Rendszerterv munkaideje: 2 óra

**Comment by Chrispy21** [comment]
Rendszerterv munkaideje: 2 óra

**Comment by ChaosOMFG** [comment]
Rendszerterv munkaideje: 2 óra
