### ISSUE TITLE
PROJEKT LEZÁRÁSA

### ISSUE THREAD

**Issue by Chrispy21** [Chrispy21/MonogameBallgame#51]
_Projekt sikeresnek tekinthető közös megegyezés alapján._

**Comment by Chrispy21** [comment]
A projekt sikeresnek tekinthető

**Comment by ChaosOMFG** [comment]
A projekt sikeresnek tekinthető

**Comment by sdavid18** [comment]
A projekt sikeres.

**Comment by markraven** [comment]
A projekt sikeresnek tekinthető.
